# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from operations_research import linear_extension_pb2 as operations__research_dot_linear__extension__pb2
from operations_research import linear_solver_pb2 as operations__research_dot_linear__solver__pb2


class LinProgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MILPModel = channel.unary_unary(
                '/operations_research.LinProgService/MILPModel',
                request_serializer=operations__research_dot_linear__solver__pb2.MPModelRequest.SerializeToString,
                response_deserializer=operations__research_dot_linear__solver__pb2.MPSolutionResponse.FromString,
                )
        self.MILPReferenceModel = channel.stream_stream(
                '/operations_research.LinProgService/MILPReferenceModel',
                request_serializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.SerializeToString,
                response_deserializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelResponse.FromString,
                )
        self.MILPReferenceBuild = channel.stream_unary(
                '/operations_research.LinProgService/MILPReferenceBuild',
                request_serializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.SerializeToString,
                response_deserializer=operations__research_dot_linear__solver__pb2.MPModelRequest.FromString,
                )


class LinProgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MILPModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MILPReferenceModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MILPReferenceBuild(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinProgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MILPModel': grpc.unary_unary_rpc_method_handler(
                    servicer.MILPModel,
                    request_deserializer=operations__research_dot_linear__solver__pb2.MPModelRequest.FromString,
                    response_serializer=operations__research_dot_linear__solver__pb2.MPSolutionResponse.SerializeToString,
            ),
            'MILPReferenceModel': grpc.stream_stream_rpc_method_handler(
                    servicer.MILPReferenceModel,
                    request_deserializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.FromString,
                    response_serializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelResponse.SerializeToString,
            ),
            'MILPReferenceBuild': grpc.stream_unary_rpc_method_handler(
                    servicer.MILPReferenceBuild,
                    request_deserializer=operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.FromString,
                    response_serializer=operations__research_dot_linear__solver__pb2.MPModelRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations_research.LinProgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LinProgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MILPModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations_research.LinProgService/MILPModel',
            operations__research_dot_linear__solver__pb2.MPModelRequest.SerializeToString,
            operations__research_dot_linear__solver__pb2.MPSolutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MILPReferenceModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/operations_research.LinProgService/MILPReferenceModel',
            operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.SerializeToString,
            operations__research_dot_linear__extension__pb2.ReferenceMPModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MILPReferenceBuild(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/operations_research.LinProgService/MILPReferenceBuild',
            operations__research_dot_linear__extension__pb2.ReferenceMPModelRequest.SerializeToString,
            operations__research_dot_linear__solver__pb2.MPModelRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
